### ISSUE TITLE
Favouriting events: Saving/removing an event or scrolling event listings page causes heart icons to flicker (iOS only)

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#221] opened 2018-05-03 13:26 UTC
## Description of issue

When on the Events listing page, tapping to add or remove an event from the saved events will cause the heart icons to flicker 

## Expected behaviour

Tapping to add/remove an event doesn't affect the icons for other saved events. 

## Steps to reproduce

- Open the "Events" page
- Favourite the top 2 events
- Repeatedly tap the heart icon for the third event
> The heart icons for the top 2 events flicker as the icon for the third event is tapped. 

## OS / Browser / Device model

iPhone 6 (10.3.3)
iPhone 7+ (10.3.1)

## Screenshots

![fave_flicker](https://user-images.githubusercontent.com/33623842/39579160-fa5f5792-4edd-11e8-9590-7a80792c2ca6.gif)

-----

I also noticed that scrolling with a bunch of favourited events visible in the events listing page will also result in the icons flickering:

![scroll_flicker](https://user-images.githubusercontent.com/33623842/39583723-abfa9656-4ee8-11e8-826b-2ac81902832d.gif)

Again, it only affects iOS so I assume it is related to the above issue - if not I can log it as a separate issue. 

It is quite easy to reproduce on iPhone 6 - I have reproduced on iPhone 7+ once or twice but it's not reliably reproducible.

**Comment by RGBboy** [comment] 2018-05-08 14:54
@declanslevin I could not reproduce this on master. There could be a chance someone has made a change to fix. Would you mind showing me this when you are in?

**Comment by stevecottle** [comment] 2018-05-10 15:51
Adding Accessibility label as the flash icons may have accessibility concerns.

**Comment by RGBboy** [comment] 2018-05-12 13:49
Fixed in #282

**Closed by RGBboy** 2018-05-12 13:49 UTC
Labels: accessibility, bug
