### ISSUE TITLE
Errors when selecting a date while filtering events by day

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#84] opened 2018-03-28 11:44 UTC
Tested on master branch with a Galaxy S8 (Android 7.0)

Opening the day filter on the Events Listing page and tapping on a day (any day) results in an error, complaining that the start of the range is after the end.

- Go to the Events Listing page
- Tap on the 'Any day' filter
- Select any day on the calendar
> Error screen shown - "Error: The start of the range cannot be after the end of the range"

Screenshot attached of the displayed error message (wasn't letting me copy it): 
![screenshot_20180328-115946](https://user-images.githubusercontent.com/33623842/38026728-23be0090-3285-11e8-92cc-4a9800e1767f.jpg)

**Comment by frigus02** [comment] 2018-03-28 13:59
I think this a duplicate of #73 (sorry I didn't put the actual error message in there).

**Closed** 2018-04-17 08:34 UTC
Labels: bug
